import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Search, RotateCcw, ExternalLink } from 'lucide-react'
import StatusBadge from './StatusBadge.jsx'
import { getStudents } from '../services/studentService.js'

export default function ActivityBrowser({ activities, basePath = '/staff/verify', title = 'Activities', withStudent = true, showReason = false, reviewActions = false }) {
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('All')
  const [category, setCategory] = useState('All')
  const [level, setLevel] = useState('All')
  const [department, setDepartment] = useState('All')
  const [year, setYear] = useState('All')
  const [dateFrom, setDateFrom] = useState('')
  const [dateTo, setDateTo] = useState('')
  const [sort, setSort] = useState('newest')
  const students = getStudents()
  const q = query.trim().toLowerCase()
  const filtered = [...activities].filter((item) => { const student = students.find((person) => String(person.id) === String(item.student_id)); return (!q || `${item.student_name} ${item.name} ${item.student_id} ${item.organizer}`.toLowerCase().includes(q)) && (status === 'All' || item.status === status) && (category === 'All' || item.category === category) && (level === 'All' || item.level === level) && (department === 'All' || student?.department === department) && (year === 'All' || student?.year === year) && (!dateFrom || item.date >= dateFrom) && (!dateTo || item.date <= dateTo) }).sort((a, b) => sort === 'oldest' ? a.date.localeCompare(b.date) : sort === 'student' ? a.student_name.localeCompare(b.student_name) : b.date.localeCompare(a.date))
  const options = (key) => [...new Set(activities.map((item) => item[key]).filter(Boolean))].sort()
  const reset = () => { setQuery(''); setStatus('All'); setCategory('All'); setLevel('All'); setDepartment('All'); setYear('All'); setDateFrom(''); setDateTo(''); setSort('newest') }
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800/60">
    <div className="border-b border-slate-100 p-4 sm:p-5 dark:border-slate-700"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-slate-900 dark:text-slate-100">{title}</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{filtered.length} record{filtered.length === 1 ? '' : 's'} found</p></div><button type="button" onClick={reset} className="inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-medium text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-700">{<RotateCcw size={15}/>}Reset</button></div>
      <div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><label className="relative sm:col-span-2"><span className="sr-only">Search activities</span><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input value={query} onChange={(e)=>setQuery(e.target.value)} className="h-10 w-full rounded-xl border border-slate-200 bg-white pl-9 pr-3 text-sm focus:border-indigo-500 focus:outline-none focus:ring-4 focus:ring-indigo-500/10 dark:border-slate-600 dark:bg-slate-700 dark:text-slate-200 dark:placeholder:text-slate-500"/></label><Select label="Status" value={status} onChange={setStatus} options={['All','Pending','Verified','Rejected','Draft']}/><Select label="Category" value={category} onChange={setCategory} options={['All',...options('category')]}/><Select label="Level" value={level} onChange={setLevel} options={['All',...options('level')]}/><Select label="Year" value={year} onChange={setYear} options={['All',...new Set(students.map(s=>s.year).filter(Boolean))]}/><label className="text-xs text-slate-500 dark:text-slate-400">From date<input aria-label="From date" type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} className="mt-1 h-10 w-full rounded-xl border border-slate-200 bg-white px-2 text-sm dark:border-slate-600 dark:bg-slate-700 dark:text-slate-200"/></label><label className="text-xs text-slate-500 dark:text-slate-400">To date<input aria-label="To date" type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)} className="mt-1 h-10 w-full rounded-xl border border-slate-200 bg-white px-2 text-sm dark:border-slate-600 dark:bg-slate-700 dark:text-slate-200"/></label><Select label="Sort" value={sort} onChange={setSort} options={['newest','oldest','student']} labels={{newest:'Newest',oldest:'Oldest',student:'Student name'}}/></div>
    </div>
    <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[900px] text-left"><thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-500 dark:bg-slate-800/50 dark:text-slate-400"><tr>{withStudent&&<th className="px-5 py-3">Student</th>}<th className="px-4 py-3">Activity</th><th className="px-4 py-3">Category / Level</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Status</th>{showReason&&<th className="px-4 py-3">Rejection reason</th>}<th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-700">{filtered.map((item)=><tr key={item.id} className="hover:bg-slate-50/70 dark:hover:bg-slate-700/30">{withStudent&&<td className="px-5 py-4"><p className="text-sm font-semibold text-slate-800 dark:text-slate-200">{item.student_name}</p><p className="text-xs text-slate-500 dark:text-slate-400">PRN {item.student_id} · Roll {item.roll_no||'—'}</p></td>}<td className="px-4 py-4"><p className="max-w-xs text-sm font-semibold text-slate-800 dark:text-slate-200">{item.name}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{item.organizer || 'Organizer not listed'}</p><p className="mt-1 text-xs text-slate-400 dark:text-slate-500">Achievement: {item.achievement||'—'}</p></td><td className="px-4 py-4 text-sm text-slate-600 dark:text-slate-400">{item.category}<p className="mt-1 text-xs text-slate-400 dark:text-slate-500">{item.level}</p></td><td className="px-4 py-4 text-sm text-slate-600 dark:text-slate-400">{item.date}</td><td className="px-4 py-4"><StatusBadge status={item.status}/></td>{showReason&&<td className="max-w-48 px-4 py-4 text-sm text-rose-700 dark:text-rose-400">{item.rejection_reason||item.remarks||'—'}<p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{item.rejected_by||''} {item.rejected_at||''}</p></td>}<td className="px-5 py-4 text-right"><div className="flex justify-end gap-1"><Link to={`${basePath}/${item.id}`} className="inline-flex items-center gap-1 rounded-lg bg-indigo-50 px-3 py-2 text-sm font-semibold text-indigo-700 hover:bg-indigo-100 dark:bg-indigo-900/30 dark:text-indigo-300 dark:hover:bg-indigo-900/50">View <ExternalLink size={14}/></Link>{reviewActions&&item.status==='Pending'&&<><Link to={`${basePath}/${item.id}?decision=Verified`} className="rounded-lg bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-700 hover:bg-emerald-100 dark:bg-emerald-900/30 dark:text-emerald-300 dark:hover:bg-emerald-900/50">Verify</Link><Link to={`${basePath}/${item.id}?decision=Rejected`} className="rounded-lg bg-rose-50 px-3 py-2 text-sm font-semibold text-rose-700 hover:bg-rose-100 dark:bg-rose-900/30 dark:text-rose-300 dark:hover:bg-rose-900/50">Reject</Link></>}</div></td></tr>)}</tbody></table></div>
    <div className="divide-y divide-slate-100 md:hidden dark:divide-slate-700">{filtered.map((item)=><article key={item.id} className="space-y-3 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-900 dark:text-slate-100">{item.name}</p>{withStudent&&<p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{item.student_name} · PRN {item.student_id} · Roll {item.roll_no||'—'}</p>}</div><StatusBadge status={item.status}/></div><div className="grid grid-cols-2 gap-2 text-sm text-slate-600 dark:text-slate-400"><span>{item.category} · {item.level}</span><span>{item.date}</span></div><p className="text-xs text-slate-500 dark:text-slate-400">{item.organizer} · {item.achievement}</p>{showReason&&item.status==='Rejected'&&<p className="text-sm text-rose-700 dark:text-rose-400">{item.rejection_reason||item.remarks||'No reason recorded.'} · {item.rejected_by||''}</p>}<div className="flex flex-wrap items-center gap-3"><Link to={`${basePath}/${item.id}`} className="inline-flex items-center gap-1 text-sm font-semibold text-indigo-700 dark:text-indigo-400">View details <ExternalLink size={14}/></Link>{reviewActions&&item.status==='Pending'&&<><Link to={`${basePath}/${item.id}?decision=Verified`} className="text-sm font-semibold text-emerald-700 dark:text-emerald-400">Verify</Link><Link to={`${basePath}/${item.id}?decision=Rejected`} className="text-sm font-semibold text-rose-700 dark:text-rose-400">Reject</Link></>}</div></article>)}</div>
    {filtered.length===0&&<div className="p-10 text-center text-sm text-slate-500 dark:text-slate-400">No {title.toLowerCase()} match these filters.</div>}
  </section>
}

function Select({label,value,onChange,options,labels={}}){return <select aria-label={label} value={value} onChange={(e)=>onChange(e.target.value)} className="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-700 focus:border-indigo-500 focus:outline-none focus:ring-4 focus:ring-indigo-500/10 dark:border-slate-600 dark:bg-slate-700 dark:text-slate-200">{options.map((o)=><option key={o} value={o}>{labels[o]||o}</option>)}</select>}
