import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Search, Users, ChevronRight } from 'lucide-react'
import StaffLayout from '../../layouts/StaffLayout.jsx'
import { getAllActivities } from '../../services/activityService.js'
import { getStudents } from '../../services/studentService.js'
import Card from '../../components/Card.jsx'
import ActivityBrowser from '../../components/ActivityBrowser.jsx'

export default function StudentDirectory(){const [query,setQuery]=useState('');const students=getStudents();const activities=getAllActivities();const filtered=students.filter(s=>`${s.name} ${s.id} ${s.roll_no} ${s.email} ${s.department} ${s.year}`.toLowerCase().includes(query.toLowerCase()));return <StaffLayout title="Search Students"><main><Heading title="Search Students" text="Find student profiles and review their activity history."/><label className="relative mb-5 block"><span className="sr-only">Search students</span><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 bg-white pl-10 pr-3 text-sm focus:border-indigo-500 focus:outline-none sm:max-w-xl"/></label><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(student=>{const own=activities.filter(a=>String(a.student_id)===String(student.id));const verified=own.filter(a=>a.status==='Verified').length;const pending=own.filter(a=>a.status==='Pending').length;const rejected=own.filter(a=>a.status==='Rejected').length;return <article key={student.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><Avatar name={student.name}/><div className="min-w-0"><h3 className="truncate font-semibold text-slate-900">{student.name}</h3><p className="text-xs text-slate-500">PRN {student.id} · Roll {student.roll_no} · {student.year||'Student'}</p></div></div><p className="mt-4 truncate text-sm text-slate-600">{student.department}</p><p className="mt-1 truncate text-sm text-slate-500">{student.email}</p><div className="mt-4 grid grid-cols-4 gap-2 rounded-xl bg-slate-50 p-3 text-center"><Metric name="Total" n={own.length}/><Metric name="Verified" n={verified}/><Metric name="Pending" n={pending}/><Metric name="Rejected" n={rejected}/></div><Link to={`/staff/students/${student.id}`} className="mt-4 flex items-center justify-between rounded-xl bg-indigo-50 px-3 py-2.5 text-sm font-semibold text-indigo-700 hover:bg-indigo-100">View Profile <ChevronRight size={17}/></Link></article>})}</div>{!filtered.length&&<Empty/>}</main></StaffLayout>}
export function StudentRecord(){const {id}=useParams();const student=getStudents().find(s=>String(s.id)===String(id));const activities=getAllActivities().filter(a=>String(a.student_id)===String(id));const verified=activities.filter(a=>a.status==='Verified').length;const pending=activities.filter(a=>a.status==='Pending').length;const rejected=activities.filter(a=>a.status==='Rejected').length;return <StaffLayout title="Student Profile"><main><Heading title="Student Profile" text="Student record and activity history."/>{!student?<Empty/>:<><section className="mb-5 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-4"><Avatar name={student.name}/><div><h2 className="text-xl font-bold text-slate-900">{student.name}</h2><p className="text-sm text-slate-500">PRN {student.id} · Roll {student.roll_no} · {student.department} · {student.year}</p><p className="mt-1 text-sm text-slate-500">{student.email} {student.phone&&`· ${student.phone}`}</p></div></div></section><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card title="Total Activities" value={activities.length} description="Student submissions" Icon={Users}/><Card title="Verified" value={verified} description="Approved" Icon={Users}/><Card title="Pending" value={pending} description="Awaiting review" Icon={Users}/><Card title="Rejected" value={rejected} description="Returned for updates" Icon={Users}/></div><ActivityBrowser activities={activities} title="Activity history" withStudent={false} basePath="/staff/verify"/></>}</main></StaffLayout>}
function Heading({title,text}){return <div className="mb-6"><p className="text-sm font-semibold text-indigo-700">Staff workspace</p><h2 className="mt-2 text-2xl font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{text}</p></div>}
function Avatar({name}){return <span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-indigo-100 font-bold text-indigo-700">{name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span>}
function Metric({name,n}){return <div><p className="text-lg font-bold text-slate-900">{n}</p><p className="text-[10px] text-slate-500">{name}</p></div>}
function Empty(){return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-slate-500"><Users className="mx-auto mb-3"/><p>No student records found.</p></div>}
